### PR TITLE
dev/database: Add DBPopulate.java and DBPopulateTest.java

### PR DESCRIPTION
**Pull request by sgoudham**
DBPopulate holds the methods for creating tables and inserting product data at the beginning of program execution

### CODE REVIEW

**Review by 2013884f — APPROVED** [review]
DBPopulate and DBPopulateTest look good.

**Review by hzl616 — APPROVED** [review]
There has been a lot done here! Great job creating the DBPopulate and test class. Glad you managed to fit a spy in as a dbPopulate instance - code coverage is increasing nicely

**Review by AlanRobinson1337 — APPROVED** [review]
Very nice new files - easily readable
Good use of functions in testing.
Other refactoring looks good

**Review by RobertRanson — APPROVED** [review]
DBPopulateTest looks great, really thorough coverage. Nice job!

**Review by erinmaria98 — APPROVED** [review]
This addition looks great. Easy to read and the refactoring looks good too.

**Pull request merged**
